# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0

      - name: Install Dependencies
        run: flutter packages get

      - name: Verify formatting
        run: dart format -l120 --output=none --set-exit-if-changed .

      - name: Generate files
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Analyze project source
        run: flutter analyze --fatal-infos --fatal-warnings lib test

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
